#!/usr/bin/env python
# coding: utf-8

# In[2]:


def nucleotide(str):
    d=dict()
    for n in str:
        if n in d:        
            d[n]+= 1
        else:
            d[n]=1
    print(d)
    print((d.get('A', 0)))
    print((d.get('C', 0)))
    print((d.get('G', 0)))
    print((d.get('T', 0)))
    
    return d    
        
        

h=nucleotide('CCGTCACGAGGCAGTAGCCAACGATCTTGTCGAAGTCTAAGGTTGGTCCGGATCTGTCACGGGTCGTCGCACTTCTTTGCAATGGATTCCACATGAAATAAGGTACCCGCCTCTAGAAAAAAGTGCGCAGTCCCGGCGCATTTCTTCGGCGACTATGGGGCGAAGCGGAGGTAGTAACACGAATTCCCTGCCAGCAGGCCAATTCGACCATCTGTGCAATTCGGGAATAATTCGACAATTCGATCTTCACGGCCGTGCATGCAACTCATTAACGAACACGTGTAGAAAACAAGACAGGTGACAGTGATCCATTGAGTCGATCCCACACTTGTACCCCCCCTGACGAACAGACCGAGGGTTAGCCAATTCGAAATCGTGCAGCCTATCCATCTCGCGCATCCGGGGGTGTCGTCCCTTCAGCGTCCGTTAATCGATGCTCATGTAGTATACAGAACGCCGATTCTATAAGCTGTTTTTAGGCAATCTTAGTCTTAAACAATACCCGGTCCCTATACACAGGCCTCTTCCAATTTAGTATAAGATCGGACTAAGCGGCTTATGAAATCAATGTGTGGGGACCCGACCCTATTTATTGGGAACCATCGGTTTGCAGGCTTAGTGTCGTGACCGACTGCTGGAGTATGTTACTATTGGGCCGAGGTGTAACTGTGCGAGGAATAGGGTGGAGCGACTTAGCATCATAATGGCATTTTTCCGAAACGTGAGGATCGGGACAGATTCGCGCTCGATGGATTTTCCCTTATTAACGATTAATGTATAAATGATGACATCGCGTATGCATCTACTGTAGTCTCATAGATCCC')



# In[ ]:




